version: '3.3'

networks:
    rubus_network:
        driver: bridge

services:
    rubus_api:
        image: golang
        restart: always
        ports:
            - 1323:1323
        privileged: true # needed to mount the overlay (can we do better?)
        volumes:
            - .:/code  # workspace is needed for development only, a custom golang image should be built for production...
            - /tftp:/tftp
            - /pxe:/pxe
            - /etc/exports:/etc/exports
        working_dir: /code
        depends_on:
            - rubus_db
            - rubus_provider
        command: go run .
        networks:
            - rubus_network

    rubus_db:
        image: postgres:latest
        environment:
            POSTGRES_DB: "rubus_db"
            POSTGRES_USER: "rubus_user"
            POSTGRES_PASSWORD: "rubus_password"
        networks:
            - rubus_network

    rubus_provider:
        build: ./providers/unifi/bash-cli
        expose:
            - 1080
        extra_hosts:
            - "poe-1.cluster.iiun.unine.ch:192.168.0.103"
        networks:
            - rubus_network
