version: '3.3'

networks:
    rubus_network:
        driver: bridge

services:
    rubus_api:
        build: .
        restart: always
        ports:
            - 8080:8080
        volumes:
            - .:/go/src/github.com/kjuvi/rubus-api  # mount workspace for development
            - /tftp:/tftp
            - /pxe:/pxe
        depends_on:
            - rubus_db
            - rubus_provider
        command: /go/bin/bee run -downdoc=true -gendoc=true
        networks:
            - rubus_network
    
    rubus_db:
        image: postgres:latest
        environment:
            POSTGRES_DB: "rubus_db"
            POSTGRES_USER: "rubus_user"
            POSTGRES_PASSWORD: "rubus_password"
        networks:
            - rubus_network
    
    rubus_provider:
        build: ./providers/unifi/python-cli
        expose:
            - 1080
        extra_hosts:
            - "poe-1.cluster.iiun.unine.ch:192.168.0.103"
        networks:
            - rubus_network
