version: '3.7'

networks:
    rubus_network:
        driver: bridge

services:
    rubus_api:
        build: .
        restart: always
        container_name: "rubus_api"
        ports:
            - 8080:8080
        volumes:
            - .:/go/src/github.com/kjuvi/rubus-api
        working_dir: /go/src/github.com/kjuvi/rubus-api
        depends_on:
            - rubus_db
            # - rubus_provider
        command: /go/bin/bee run -downdoc=true -gendoc=true
        networks:
            - rubus_network
    
    rubus_db:
        image: postgres:latest
        container_name: "rubus_db"
        environment:
            POSTGRES_DB: "rubus_db"
            POSTGRES_USER: "rubus_user"
            POSTGRES_PASSWORD: "rubus_password"
        networks:
            - rubus_network
    
    rubus_provider:
        build: ./providers/unifi/bash-cli
        container_name: "rubus_provider"
        expose:
            - 1080
        extra_hosts:
            - "poe-1.cluster.iiun.unine.ch:192.168.0.103"
        networks:
            - rubus_network
